### ISSUE TITLE
Add option to display warnings in a more minimal way

### ISSUE THREAD

**Issue by programmdesign** [MrBartusek/MeteoalarmCard#133]
**Is your feature request related to a problem? Please describe.**
First of all, thank you for this card! I am using it in my dashboards to show weather warnings. As space on dashboards is precious, it would be great, if there was an option to display a more minimal version of the plugin.

**Describe the solution you'd like**
It would be great, if there was an option to either show a more minimalistic card and/or the same card but with an height height of e.g, just 60px (e.g., compare the one-line glance card in the screenshot for the height I'm looking for).

**Additional context**
![image](https://user-images.githubusercontent.com/4633284/207041488-ff61e4ce-68e7-494e-a680-6c0439d89d3c.png)

**Comment by raetha** [comment]
I’ll add here that if you look at default Home Assistant cards these days, the white space around the border in much smaller, and the corners are rounded. It would be nice if the card used the HA default styles, but maybe added some yaml settings that people could use to override.

**Comment by MrBartusek** [comment]
> I’ll add here that if you look at default Home Assistant cards these days, the white space around the border in much smaller, and the corners are rounded.

Actually, corners are rounded idk what happened here

![image](https://user-images.githubusercontent.com/23432278/216761943-4ac67e95-4c0f-4935-b0d9-82989034c870.png)

And for margins, yeah it should be more consistent.

> It would be nice if the card used the HA default styles, but maybe added some yaml settings that people could use to override.

https://github.com/thomasloven/lovelace-card-mod works great if you want to modify default styles

**Comment by raetha** [comment]
@programmdesign, as a test I added the following to the bottom of my MeteoalarmCard YAML to get a shrunken version. This does work, though I've always preferred not to be dependent on additional custom components when I don't need to be.

```
card_mod:
  style: |
    ha-card .content {
      padding: 16px;
    }
    ha-card .headline {
      margin-left: 0px;
    }
    ha-card .main-icon {
      --mdc-icon-size: 40px;
      height: 40px;
    }
```

@MrBartusek, since this worked, I'll close my accidentally duplicated issue to this one. I also got the corners working correctly after trying to manually modify stuff. I'd still love to see the default CSS values adjusted as shown above, but this is a workable solution. Thanks so much for pointing out card-mod!

**Comment by MrBartusek** [comment]
Hey i was thinking abot that issue recently and for the things that came up

I understand that we should keep uniform colours, spacings and general feel of the cards in line with the rest of the home assistants but in this case, I think that makes the card wired. Although currently, paddings are larger than regular HA cards making them uniform moves the icons too much to the left, see the image below. I think that the best case for now is to just keep these paddings as they are.

![image](https://user-images.githubusercontent.com/23432278/222901519-5a9826ce-1aae-4223-af9e-cb0215868c73.png)

And for the

> It would be great, if there was an option to either show a more minimalistic card and/or the same card but with an height height of e.g, just 60px (e.g., compare the one-line glance card in the screenshot for the height I'm looking for).

I don't want to support multiple styles of card. Since adding this style that you have suggested will be just a second option to select on card configuration. If users want to change the look of the card that drastically they are able to just use card-mod.
