### ISSUE TITLE
Please provide new integrations for austrian wether service geosphere and ubimet

### ISSUE THREAD

**Issue by Alfred99-HA** [MrBartusek/MeteoalarmCard#245]
Austria has two weather services ho provide weather alarms. Since they differ pretty much, it would be nice to support both and be able to integrate both

Webpages are:
- [Geosphere (former ZAMG)](https://warnungen.zamg.at)
-  [Ubimet](https://uwz.at/)
Many thanks in advance!

**Comment by Alfred99-HA** [comment]
- geosphere pushes it weatherwarnings to [meteoalarm](https://www.meteoalarm.org) anyway, thus no new itegration is necessary
-  Ubimet provides weatherwarnings for Austria under https://uwz.at/de, for germany under https://uwr.de/ and for swiss under https://unwetter.ch/de. However I have no information found what are the possible warnings.

Thus you might close my request.
-

**Comment by a7rk** [comment]
@MrBartusek Would you be against reopening this? Meteoalarm only provides the warning on district (Bezirk) level whereas Geosphere provides warnings on municipality (Gemeinde) level.
Geosphere also provides an API that polls warnings using coordinates. I can imagine this could be used to get warnings based on Area coordinates.

Geosphere API documentation: https://openapi.hub.geosphere.at/warnapi/v1/

**Comment by MrBartusek** [comment]
Hello @a7rk. This issue was closed almost two years ago, in such cases, please open a new issue instead of commenting here.

MeteoalarmCard supports Home Assistant integrations, not APIs directly. This card only reads data from entities that already exist in HA. So for Geosphere to be supported, there would first need to be a Home Assistant integration for it (core or custom). If such an integration exists, feel free to link it in the new issue along with a list of possible warning types, and I can look into supporting it.
