### ISSUE TITLE
Burze.dzis.net integration

### ISSUE THREAD

**Issue by Abbadon89** [MrBartusek/MeteoalarmCard#67]
**Is your feature request related to a problem? Please describe.**
FEATURE REQUEST - BURZE.DZIS.NET
**Describe the solution you'd like**
There is great sensor made by Piotr:
https://github.com/PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net

Thanks for great work,

**Comment by MrBartusek** [comment]
Hey, thanks for the idea! Just letting you know that this request will take longer than usual since NINA integration creates multiple sensors for the alerts and the card is not really designed for that kind of integration. There are some major changes that need to be made to allow for that kind of sensor.

**Comment by MrBartusek** [comment]
This integration is now part of the new beta version [`v2.0.0-rc.1`](https://github.com/MrBartusek/MeteoalarmCard/releases/tag/v2.0.0-rc.1). You can help to test changes in the new release. See more here: #88
