### ISSUE TITLE
Support for NINA (civil protection warnings in Germany)

### ISSUE THREAD

**Issue by GitHubUser325** [MrBartusek/MeteoalarmCard#71]
Hi buddy! Thanks for this fantastic Card! DWD alerts are working properly! (Y)

Is it possible to add Support for the new, official NINA Integration [https://www.home-assistant.io/integrations/nina/](https://www.home-assistant.io/integrations/nina/)

Would be awesome! 

Thanks in advance and Greets!

**Comment by andybali** [comment]
+1

**Comment by DeerMaximum** [comment]
I am currently working on an update that will make the warnings accessible via one sensor to support this card.
If any other attributes or information is needed please contact me.

PR: https://github.com/home-assistant/core/pull/69804

**Comment by MrBartusek** [comment]
@DeerMaximum Hey, thanks for that! I don't really think there are any more attributes needed to be added. Support for NINA will be added soon regardless of https://github.com/home-assistant/core/pull/69804. Since it seems to be a trend popping up in HA to separate data into more entities, there soon will be an update to the card which will allow providing list of entities rather than only one. This will also allow to start working on #67 which, same as the current NINA, is separated into many entities.

**Comment by MrBartusek** [comment]
Hey, thanks for the suggestion! NINA integration was added to the [2.0](https://github.com/MrBartusek/MeteoalarmCard/tree/2.0) branch. You will be able to use this integration starting from version `v2.0.0` which will be released soon.

**Comment by MrBartusek** [comment]
This integration is now part of the new beta version [`v2.0.0-rc.1`](https://github.com/MrBartusek/MeteoalarmCard/releases/tag/v2.0.0-rc.1). You can help to test changes in the new release. See more here: #88
