### ISSUE TITLE
Determine language based on user preference in HA 

### ISSUE THREAD

**Issue by groenmarsmannetje** [MrBartusek/MeteoalarmCard#79]
**Describe the bug**
Currently the card is using the os/browser language setting to display translated texts on card.
Most other cards in HA do this based on the user preference in HA.
This results in language inconsistency on a HA dashboard when both language settings are not the same.

**To Reproduce**
1. Make your os/browser language setting different then your language preference in HA
2. Open dashboard in HA and see difference in behavior with other cards

**Expected behavior**
All cards in HA should follow same mechanism to determine preferred language.

**Screenshots**
See example below. The os/browser is in English, the user preference in HA is in Dutch.

![image](https://user-images.githubusercontent.com/46958454/162218428-27bcb350-591e-47b2-ba73-927754d1c050.png)

**System (please complete the following information):**
 - Card version: 1.14.1
 - Integration type: Core
 - Installation type: HACS

**Comment by MrBartusek** [comment]
Hey, the card actually uses the HA language first and then falls back to browser one. The text that you are seeing `Moderate wind warning` is the headline provided by integration, not the card. This is probably because you didn't set the [language variable](https://www.home-assistant.io/integrations/meteoalarm/#language) while configuring your Meteoalarm integration. The other solution is to enable `override_headline` while configuring Meteoalarm Card, that will bypass headling provided by integration.

**Comment by MrBartusek** [comment]
@andybali the warning that you see on dekstop is too wide to fit on mobile and thus it falls back to headline generated by card in lanugage set in your app preferences.

**Comment by andybali** [comment]
"...in lanugage set in your app preferences." - No, there I also set "de" (German)

**Comment by MrBartusek** [comment]
@andybali Hey, this sounds like a bigger problem! Can you [create a new issue](https://github.com/MrBartusek/MeteoalarmCard/issues/new?assignees=&labels=bug&template=bug_repport.yaml) with as much details as you can get including screenshots of language settings? Thanks!

**Comment by andybali** [comment]
done #101
